<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="med000008316" failures="1" tests="2" name="Default test" time="103.564" errors="0" timestamp="26 feb. 2019 13:49:50 GMT+00:00">
  <testcase classname="died_procesos_generales.pgPerfilTest.PerfilTest" name="PerfilCaseTest01" time="86.69"/>
  <testcase classname="died_procesos_generales.pgPerfilTest.PerfilTest" name="PerfilCaseTest02" time="7.428">
    <failure type="java.lang.AssertionError" message="expected [¿Desea actualizar su número de teléfono fijo?] but found [El número de teléfono ingresado es idéntico al actual, por favor verifique.]">
      <![CDATA[java.lang.AssertionError: expected [¿Desea actualizar su número de teléfono fijo?] but found [El número de teléfono ingresado es idéntico al actual, por favor verifique.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at died_procesos_generales.pgPerfilPage.PerfilPage.verifyMessage01_aroundBody40(PerfilPage.java:430)
	at died_procesos_generales.pgPerfilPage.PerfilPage$AjcClosure41.run(PerfilPage.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
	at died_procesos_generales.pgPerfilPage.PerfilPage.verifyMessage01(PerfilPage.java:430)
	at died_procesos_generales.pgPerfilTest.PerfilTest.PerfilCaseTest02(PerfilTest.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- PerfilCaseTest02 -->
</testsuite> <!-- Default test -->
